# Generated by Django 5.0.4 on 2024-04-29 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_carmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='emyearp_city',
            new_name='year',
        ),
    ]
